#!/usr/bin/env python3
"""Turns the two folium maps from the taxi-ml project into light data files for the website.

    python3 tools/prep_taxi_data.py  path/to/tip_map.html  path/to/tip_map_timeslices.html

The folium files are 12 and 20 MB because the zone polygons are repeated in every layer. This reads the
polygons and per-zone numbers once, simplifies the shapes, and writes

    js/taxi-data.js        zone outlines (SVG paths) and the numbers behind every map layer
    tools/taxi_thumb.svg   the little map used on the project card

Needs shapely (pip install shapely). Run from the site root.
"""
import json
import math
import os
import re
import sys

from shapely.geometry import shape

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(root)

if len(sys.argv) != 3:
    sys.exit(__doc__)


def first_geojson(path):
    """The first GeoJSON FeatureCollection in a folium file (later layers repeat the same polygons)."""
    text = open(path, encoding="utf-8").read()
    m = re.search(r"geo_json_[0-9a-f]+_add\(\{", text)
    obj, _ = json.JSONDecoder().raw_decode(text[m.end() - 1:])
    return obj


jan = first_geojson(sys.argv[1])    # decision tree, January hold-out: actual / predicted / error by pickup zone
ts = first_geojson(sys.argv[2])     # weekday rush vs. Fri/Sat night, February (a month the model never saw)
by_id_ts = {f["properties"]["LocationID"]: f["properties"] for f in ts["features"]}

LON0, LAT0, SCALE = -74.0, 40.7, 2200.0
COS = math.cos(math.radians(LAT0))


def xy(lon, lat):
    return (lon - LON0) * COS * SCALE, -(lat - LAT0) * SCALE


def path_d(geom, tol, digits=1):
    g = shape(geom).simplify(tol, preserve_topology=True)
    polys = [g] if g.geom_type == "Polygon" else list(g.geoms)
    parts = []
    for poly in polys:
        for ring in [poly.exterior, *poly.interiors]:
            pts = [xy(*p) for p in ring.coords]
            parts.append("M" + "L".join(f"{x:.{digits}f} {y:.{digits}f}" for x, y in pts[:-1]) + "Z")
    return "".join(parts)


def num(v, nd=3):
    return None if v is None or v != v else round(float(v), nd)


zones = []
minx = miny = 1e9
maxx = maxy = -1e9
for f in jan["features"]:
    p = f["properties"]
    q = by_id_ts[p["LocationID"]]
    d = path_d(f["geometry"], 0.0004)
    lo, la, hi, ha = shape(f["geometry"]).bounds
    (bx0, by1), (bx1, by0) = xy(lo, la), xy(hi, ha)
    minx, maxx = min(minx, bx0), max(maxx, bx1)
    miny, maxy = min(miny, by0), max(maxy, by1)
    zones.append({
        "id": p["LocationID"], "z": p["zone"], "b": p["borough"], "d": d,
        # January hold-out: trips, actual share, model probability, predicted - actual, average fare
        "j": [int(p["trips"]) if p["trips"] == p["trips"] and p["trips"] is not None else 0,
              num(p["actual_rate"]), num(p["pred_rate"]), num(p["gap"]), num(p["avg_fare"], 2)],
        # February: weekday rush [trips, actual, predicted], Fri/Sat night [trips, actual, predicted]
        "r": [int(q["trips_rush"]), num(q["actual_rush"]), num(q["pred_rush"])],
        "n": [int(q["trips_night"]), num(q["actual_night"]), num(q["pred_night"])],
    })

pad = 12
vb = [round(minx - pad), round(miny - pad), round(maxx - minx + 2 * pad), round(maxy - miny + 2 * pad)]
data = {"viewBox": vb, "zones": zones}
with open("js/taxi-data.js", "w", encoding="utf-8") as fh:
    fh.write("/* Generated by tools/prep_taxi_data.py from the taxi-ml folium maps. Do not edit by hand. */\n")
    fh.write("window.TAXI_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
print("wrote js/taxi-data.js", os.path.getsize("js/taxi-data.js") // 1024, "KB;", len(zones), "zones")

# ---------------------------------------------------------------- card thumbnail: Manhattan and its neighbors
# crop window in the same projected coordinates (Manhattan runs from the Battery up to Inwood)
lo_lon, hi_lon, lo_lat, hi_lat = -74.03, -73.90, 40.69, 40.88
x0, y1 = xy(lo_lon, lo_lat)
x1, y0 = xy(hi_lon, hi_lat)
fills, lines = [], []
for f in jan["features"]:
    p = f["properties"]
    g = shape(f["geometry"])
    cx, cy = g.centroid.x, g.centroid.y
    if not (lo_lon <= cx <= hi_lon and lo_lat <= cy <= hi_lat):
        continue
    d = path_d(f["geometry"], 0.0006)
    lines.append(d)
    r = p["actual_rate"]
    if r is not None and r == r and p["borough"] == "Manhattan":
        op = 0.12 + 0.75 * max(0.0, min(1.0, (r - 0.45) / 0.3))
        fills.append(f'<path class="fa" style="fill-opacity:{op:.2f}" d="{d}"/>')
w, h = x1 - x0, y1 - y0
svg = (f'<svg viewBox="{x0:.0f} {y0:.0f} {w:.0f} {h:.0f}" role="img" aria-label="Map of Manhattan taxi zones shaded by '
       f'the share of generous tips" xmlns="http://www.w3.org/2000/svg">' + "".join(fills) +
       '<path class="s" d="' + "".join(lines) + '"/></svg>')
open("tools/taxi_thumb.svg", "w", encoding="utf-8").write(svg)
print("wrote tools/taxi_thumb.svg", len(svg) // 1024, "KB")
